name: liferea
version: '0.1' # just for humans, typically '1.2+git' or '1.3.2'
summary: The free news aggregator on your Linux desktop
description: |
  Liferea is a web feed reader/news aggregator that brings together all of
  the content from your favorite subscriptions into a simple interface that
  makes it easy to organize and browse feeds. Its GUI is similar to a
  desktop mail/newsclient, with an embedded graphical browser.
icon: pixmaps/scalable/liferea.svg

grade: stable
confinement: devmode # use 'strict' once you have the right plugs and slots

plugs:
  gnome-3-24-platform:
    interface: content
    target: gnome-platform
    default-provider: gnome-3-24:gnome-3-24-platform

apps:
  liferea:
    desktop: usr/share/applications/liferea.desktop
    command: |
      desktop-launch pulse-launch env PYTHONHOME=$SNAP/usr snapcraft-preload $SNAP/usr/bin/liferea
    plugs:
      - gnome-3-24-platform
      - gsettings
      - home
      - network
      - network-bind
      - network-observe
      - opengl
      - pulseaudio
      - unity7
      - x11

parts:
  prepare:
    plugin: nil
    prepare: |
      echo "deb http://ppa.launchpad.net/ubuntu-desktop/gnome-3-24/ubuntu xenial main" | tee /etc/apt/sources.list.d/gnome-3-24.list
      apt-key adv --keyserver keyserver.ubuntu.com --recv-keys 399B698EEA9EF163B6F9A0F62CC98497A1231595
      apt update
      apt upgrade -yy

  pulse-launch:
    plugin: dump
    source: snap-files
    prepare: |
      chmod +x pulse-launch
    organize:
      pulse-launch: bin/pulse-launch

  snapcraft-preload:
    source: https://github.com/sergiusens/snapcraft-preload.git
    plugin: cmake
    build-packages: [g++-multilib]

  liferea:
    plugin: autotools
    source: https://github.com/lwindolf/liferea/releases/download/v1.10.19/liferea-1.10.19.tar.bz2
    configflags:
      - --prefix=/snap/liferea/current/usr
    organize:
      snap/liferea/current/usr: usr
    build-packages:
      - intltool
      - libgirepository1.0-dev
      - libgstreamer-plugins-bad1.0-dev
      - libgstreamer-plugins-base1.0-dev
      - libgstreamer-plugins-good1.0-dev
      - libgstreamer1.0-dev
      - libjson-glib-dev
      - libnotify-dev
      - libpeas-dev
      - libpulse-dev
      - libsqlite3-dev
      - libwebkitgtk-3.0-dev
      - libxml2-dev
      - libxslt1-dev
      - gsettings-desktop-schemas-dev
      - python2.7-dev
    stage-packages:
      - gir1.2-gst-plugins-bad-1.0
      - gir1.2-gst-plugins-base-1.0
      - gir1.2-gstreamer-1.0
      - gir1.2-gtk-3.0
      - gir1.2-peas-1.0
      - gstreamer1.0-fluendo-mp3
      - gstreamer1.0-libav
      - gstreamer1.0-plugins-base
      - gstreamer1.0-plugins-good
      - gstreamer1.0-pulseaudio
      - libgirepository-1.0-1
      - libgstreamer-plugins-bad1.0-0
      - libgstreamer-plugins-base1.0-0
      - libgstreamer-plugins-good1.0-0
      - libgstreamer1.0-0
      - libpeas-1.0-0
      - libpeas-1.0-0-python2loader
      - libpulse0
      - libwebkitgtk-3.0-0
      - python2.7
      - python-gi
    after: [desktop-gnome-platform, prepare]
    # prime:
    #   - usr/bin/liferea*
    #   - usr/bin/py*
    #   - usr/lib/libpeas*
    #   - usr/lib/liferea
    #   - usr/lib/python*
    #   - usr/lib/**/caca
    #   - usr/lib/**/gstreamer1.0
    #   - usr/lib/**/gstreamer-1.0
    #   - usr/lib/**/libaa*
    #   - usr/lib/**/libavc1394*
    #   - usr/lib/**/libbluray*
    #   - usr/lib/**/libcaca*
    #   - usr/lib/**/libcdda*
    #   - usr/lib/**/libcroco*
    #   - usr/lib/**/libcrystalhd*
    #   - usr/lib/**/*ffmpeg*
    #   - usr/lib/**/libffi*
    #   - usr/lib/**/libFLAC*
    #   - usr/lib/**/libflite*
    #   - usr/lib/**/libgirepository*
    #   - usr/lib/**/libgst*
    #   - usr/lib/**/libICE*
    #   - usr/lib/**/libjack*
    #   - usr/lib/**/libjavascriptcoregtk*
    #   - usr/lib/**/libmodplug*
    #   - usr/lib/**/libmp3lame*
    #   - usr/lib/**/libmpdec*
    #   - usr/lib/**/libogg*
    #   - usr/lib/**/libopencv*
    #   - usr/lib/**/libopus*
    #   - usr/lib/**/liborc*
    #   - usr/lib/**/libpeas*
    #   - usr/lib/**/libpulse*
    #   - usr/lib/**/libraw1394*
    #   - usr/lib/**/librom1394*
    #   - usr/lib/**/libsamplerate*
    #   - usr/lib/**/libschroedinger*
    #   - usr/lib/**/libshout*
    #   - usr/lib/**/libSM*
    #   - usr/lib/**/libsndfile*
    #   - usr/lib/**/libsodium*
    #   - usr/lib/**/libsoxr*
    #   - usr/lib/**/libspeex*
    #   - usr/lib/**/libtag*
    #   - usr/lib/**/libtheora*
    #   - usr/lib/**/libtwolame*
    #   - usr/lib/**/libv4l*
    #   - usr/lib/**/libva*
    #   - usr/lib/**/libvorbis*
    #   - usr/lib/**/libvpx*
    #   - usr/lib/**/libwavpack*
    #   - usr/lib/**/libwebkitgtk*
    #   - usr/lib/**/libx264*
    #   - usr/lib/**/libx265*
    #   - usr/lib/**/libXt.so*
    #   - usr/lib/**/x264-10bit
    #   - usr/share/appdata/liferea*
    #   - usr/share/applications/liferea*
    #   - usr/share/GConf/gsettings/liferea*
    #   - usr/share/glib-2.0/schemas/*liferea*
    #   - usr/share/icons/**/liferea*
    #   - usr/share/liferea
    #   - usr/share/locale/**/liferea*
    #   - usr/share/webkitgtk-3.0